import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


const Home= () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amarilis Next</title>
        <meta name="keywords" content=""></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello <a href="https://nextjs.org">World!</a></h1>
        <Image 
          src="/images/google.jpg" 
          width="300px" 
          height="150px" 
          alt="google"
        />
      </main>
    </div>
  )
}
export default Home;